services:
  postgres:
    image: postgres:16
    container_name: eventory-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGNAME}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: